config/routes.rb
Seoulaz::Application.routes.draw do

  root :to => 'welcome#index'
  resources :articles do 
    collection do
      get 'latests'
    end
  end

  resources :energyconsumes
  resources :business_seouls
  
  resources :edu_percentages
  resources :edu_satisfactories
  resources :edu_supports
  resources :public_restrooms
  resources :edu_academies, :only => [:index] do 
    collection do 
      get 'all_index'
    end
  end

  
  namespace :admin do 
    resources :articles
    root :to => 'articles#index'
  end
  

end

app/models/article.rb
class Article < ActiveRecord::Base

  def conv_to_json(template)
    {
      :id => self.id,
      :title => self.title,
      :description => self.description,
      :template => template
    }
  end
end

app/controllers/admin/articles_controller.rb
#encoding: utf-8
class Admin::ArticlesController < Admin::AdminController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])

    if @article.save
      redirect_to admin_articles_path, :notice => '성공적으로 저장'
    else 
      redirect_to request.referer, :alert => '실패'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update_attributes(params[:article])
      redirect_to admin_articles_path, :notice => '성공적으로 업데이트'
    else 
      redirect_to request.referer, :alert => '실패'
    end
  end

  def destroy
    @article = Article.find(params[:id])

    @article.destroy
    redirect_to admin_articles_path, :notice => '성공적으로 삭제'
  end
end

app/controllers/articles_controller.rb
#encoding: utf-8
class ArticlesController < ApplicationController
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::UrlHelper
  include Sprockets::Helpers::RailsHelper
  include Sprockets::Helpers::IsolatedHelper
  include ActionView::Helpers::AssetTagHelper

  def latests
    @articles = Article.order('updated_at DESC').limit(3)
    if @articles.present?

      @articles_json = get_articles_json(@articles)

      
      render :json => {:success => true, :articles => @articles_json }
    else
      render :json => {:success => false, :message => '글이 없습니다.' }
    end
  end

  def show
    @article = Article.find(params[:id]) 

    if @article.present?
      erb_renderer = ERB.new(@article.template)
      @rendered_page_template = erb_renderer.result(binding)

      render :json => {:success => true, :article => @article.conv_to_json(@rendered_page_template)}
    else
      render :json => {:success => false, :message => '글이 없습니다.' }
    end
  end

  private

  def get_articles_json(articles)

    articles_json = []

    articles.each do |article|
      @article = article
      if article.template_path.present?
        erb_renderer = ERB.new(File.read(Rails.root.to_s + article.template_path))
        @rendered_page_template = erb_renderer.result(binding)
      else 
        erb_renderer = ERB.new(@article.template)
        @rendered_page_template = erb_renderer.result(binding)
      end

      articles_json << @article.conv_to_json(@rendered_page_template)

    end

    articles_json
  end

end

app/views/admin/articles/_form.html.erb
<%= form_for [:admin, @article], :html => {:class => 'form-horizontal'} do |f| %>
  <div class="control-group">
    <%= f.label :title, '제목', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'input-xlarge' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description, '설명', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'input-xlarge span10', :style => 'height:200px' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :template_path, '템플릿 경로', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :template_path, :class => 'input-xlarge' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :template, '템플릿', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :template, :class => 'input-xlarge span10', :style => 'height:500px' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit '저장', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<h2>
  수정
</h2>
<%= render 'form' %>

app/views/admin/articles/index.html.erb
<h2>
  articles
</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>
          제목
        </th>
        <th>
          업로드일
        </th>
        <th>
          삭제
        </th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td>
            <%= link_to article.title, edit_admin_article_path(article) %>
          </td>
          <td>
            <%= article.updated_at.strftime('%Y/%m/%d') %>
          </td>
          <td>
            <%= link_to '삭제', admin_article_path(article), :method => :delete, :confirm => '정말 삭제하시겠습니까?' %>
          <td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to '새 주제글 추가', new_admin_article_path, :class => 'btn' %>

app/views/admin/articles/new.html.erb
<h2>
  새 글
</h2>
<%= render 'form' %>